### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by GabrielLin** [IllDepence/ecir2020#2]
Could you please provide a tutorial, please? Thanks.

**Comment by IllDepence** [comment]
Hi,

could you elaborate a bit?
E.g.: Is your goal to replicate the evaluation results described in the paper or something different? W.r.t. your goal, where are you stuck? Is something within the paper unclear or rather in the code?

Cheers

**Comment by GabrielLin** [comment]
> Hi,
> 
> could you elaborate a bit?
> E.g.: Is your goal to replicate the evaluation results described in the paper or something different? W.r.t. your goal, where are you stuck? Is something within the paper unclear or rather in the code?
> 
> Cheers

Thanks for your reply. My goal is to replicate the evaluation results described in the paper. I hope a tutorial including environment information, package versions, which files to run and their parameters, etc. Thanks.

**Comment by IllDepence** [comment]
Hi GabrielLin,

apologies for the late reply.
The core of the offline evaluation is `code_offline_eval/evaluate.py`, executed as

`python3 evaluate.py </path/to/context_csv> </path/to/gensim_dict> [<claim_gensim_dict>] [<np_gensim_dict>]`
(by the way, if you just execute `python3 evaluate.py` you will be presented with this information as well)

The first two positional arguments are mandatory, while the third and fourth are only needed for evaluation of the claim and NP based models respectively. As for the four arguments:

* `context_csv`: has to be structured like `code_offline_eval/example_contexts.csv`
    * i.e. the fields `<cited_doc_MAG_ID>`, `<adjacent_cited_docs_MAG_IDs>`, `<citing_doc_arXiv_ID>`, `<citation_context>`, `<MAG_field_of_study_annotation>`, `<PredPatt_claim_annotation>`, `<noun_phrases>` separated by a `U+241E` (record separator).  The fields `<adjacent_cited_docs_MAG_IDs>` and `<noun_phrases>` are lists of elements separated by a `U+241F` (unit separator)
    * `<PredPatt_claim_annotation>`: generated with `code_offline_eval/preprocessing/predpatt_extend_contexts.py`
    * `<noun_phrases>`: generated with `code_offline_eval/preprocessing/noun_phrase_extend_contexts.py` based on `code_offline_eval/preprocessing/noun_phrases.txt_compressed.xz`
* `gensim_dict` / `claim_gensim_dict` / `np_gensim_dict`: all generated using `code_offline_eval/preprocessing/generate_gensim_dict.py`

Regarding environment information and package versions, please look at `code_offline_eval/requirements.txt`.

**Comment by GabrielLin** [comment]
@IllDepence  Thank you very much. Let me try it.

**Comment by GabrielLin** [comment]
@IllDepence I have already downloaded your dataset unarXive and MAG. How can I generate `context_csv` using those datasets? Thanks.

**Comment by IllDepence** [comment]
Hi GabrielLin,

as for unarXive, I presume you have a directory `code/`. Correct? Within that directory, locate the file `README` . It reads: *"Use the script extract_contexts.py to create your own, custom citation context extracts."*. You can use the script to generate a context CSV.

For the MAG, have a look at its [schema](https://docs.microsoft.com/en-us/academic-services/graph/reference-data-schema#papercitationcontextstxt). You'll find that there is a table `PaperCitationContexts`, which you can use in combination with the other tables to generate a contexts CSV in the required format.

**Comment by GabrielLin** [comment]
Thanks. I am trying. I think it will cost me a lot of time to run.

**Comment by GabrielLin** [comment]
I am not sure whether my operation is correct or not.

I downloaded unarXive at the project root path and unzip it. Then I switch to the project root path and run `python code_offline_eval/preprocessing/generate_gensim_dict.py unarXive/contexts/extracted_contexts.csv` to generate gensim dicts.

The following error is shown:
```
0/29203190 lines
Traceback (most recent call last):
  File "code_offline_eval/preprocessing/generate_gensim_dict.py", line 82, in <module>
    build(docs_path)
  File "code_offline_eval/preprocessing/generate_gensim_dict.py", line 58, in build
    for weight, terms in pp_lists:
TypeError: 'float' object is not iterable
```

Could you help? Thanks.

**Comment by IllDepence** [comment]
As unarXive is not a dedicated data set for this very project, the CSV column formats are not compatible out of the box. You will have to make sure that the CSV you use with `generate_gensim_dict.py` adheres to one of the input formats (in terms of number and arrangement of columns) the script understands.
