### ISSUE TITLE
Broken link of ACL-ARC

### ISSUE THREAD

**Issue by GabrielLin** [IllDepence/ecir2020#3]
I am afraid that the link of ACL-ARC is broken. Could you please upload that dataset please? Really thanks.

**Comment by IllDepence** [comment]
Hi GabrielLin,

thank you for the info. You could try contacting the people at [ACL](https://www.aclweb.org/). I'm afraid I can't just upload other people's data sets without the explicit right for distribution. (Privately sharing it might be an option though.)

**Comment by GabrielLin** [comment]
OK. Let's communicate with email. Thanks.
