### ISSUE TITLE
How to construct this format by a given sentence？

### ISSUE THREAD

**Issue by jennifer1995** [IllDepence/ecir2020#4]
As you mention in https://github.com/IllDepence/ecir2020/issues/2, there should be a context file like `code_offline_eval/example_contexts.csv`. 

Could you please tell me how to construct this format by a given sentence please? 

Espeically something like
 `[[1, ["allow:result", "allow:more sophisticated methods", "allow:bayesian optimization", "allow:date", "allow:run", "allow:parallel", "allow:cost", "allow:optimization method", "allow:space", "allow:trivial yet effective parallelization", "allow:simple approach", "allow:parallelization", "allow:hyperparameter", "allow:independent runs", "allow:optimization process", "allow:hyperparameter configurations", "allow:empirical evidence", "allow:bayesian", "allow:methods", "allow:lowest cross validation error", "allow:optimization", "perform:independent runs", "perform:run", "perform:result", "perform:parallel", "perform:optimization method", "perform:lowest cross validation error", "perform:optimization", "select:lowest cross validation error", "select:run", "select:result", "exist:bayesian optimization", "exist:parallelization", "exist:bayesian", "exist:more sophisticated methods", "be:hyperparameter configurations", "be:cost", "be:empirical evidence", "be:simple approach", "be:hyperparameter", "be:methods", "be:date", "be:space", "outperform:hyperparameter configurations", "outperform:cost", "outperform:simple approach", "outperform:hyperparameter", "outperform:methods", "outperform:space", "use:cost", "use:space", "use:hyperparameter", "use:hyperparameter configurations", "vary:cost", "vary:space", "vary:hyperparameter", "vary:hyperparameter configurations"]]]`. 
Thanks.

**Comment by IllDepence** [comment]
Hi,

in general you can refer to [this description in Issue #2](https://github.com/IllDepence/ecir2020/issues/2#issuecomment-690911733).

The example annotation you give is created using [PredPatt](https://github.com/hltcoe/PredPatt) and generated with `code_offline_eval/preprocessing/predpatt_extend_contexts.py` (generation process also described in the paper).

To give a bit more detail and background information, although I unfortunately can't provide a nice documentation:

* Except for the last few fields in the CSV, the files were created using [this script](https://github.com/IllDepence/master_thesis/blob/2d2e9cb38d688a293381817f4442e649e40f8072/code/recommender_claim/generate_dataset.py), based on an early version of the [unarXive](https://github.com/IllDepence/unarXive) `refs.db` data base.
* the fields `<cited_doc_MAG_ID>`, `<adjacent_cited_docs_MAG_IDs>`, and `<citing_doc_arXiv_ID>` are metadata depending on the citing and cited document
*  `<citation_context>` is the citation context ("sentence") itself 
* `<MAG_field_of_study_annotation>` is created in abovementioned script in [line 237](https://github.com/IllDepence/master_thesis/blob/2d2e9cb38d688a293381817f4442e649e40f8072/code/recommender_claim/generate_dataset.py#L237)
* `<PredPatt_claim_annotation>`, as stated above, is generated with `code_offline_eval/preprocessing/predpatt_extend_contexts.py`
* `<noun_phrases>` is generated with `code_offline_eval/preprocessing/noun_phrase_extend_contexts.py` based on `code_offline_eval/preprocessing/noun_phrases.txt_compressed.xz`

Hope this helps.

**Comment by jennifer1995** [comment]
Thank you very much!
